### PR TITLE
Add MC recipe and remove ludicrous ichorium one

### PR DESCRIPTION
**Pull request by Prometheus0000**
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6321, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7863.

### CODE REVIEW

**Comment by Dream-Master** [comment]
why you remove it? I like a technical way to get ichorium

**Comment by Prometheus0000** [comment]
Because it's ludicrous? Did you read the issue?

**Comment by Dream-Master** [comment]
yes but why we dont cahnge/balance the recipe a bit?

**Comment by Prometheus0000** [comment]
Well, personally I don't think you should be making magic materials with tech, it's magic after all. If you can do it without magic, it skips over all the magic stuff which seems unfair to the people who did that. Plus if it's easier than the magic way no one will do it that way.

I can still change it if you want me to though.

**Comment by Prometheus0000** [comment]
If you look at the recipes right above it you can see you can basically turn iron -> thaumium -> void -> shadow -> ichorium.

Personally, I'd rather disable all of these actually. You don't need to do any research or understand thaum at all to get any of this stuff. Or get any warp, which you normally need.

**Comment by Dream-Master** [comment]
sure a rework is maybe necessary. Lets see what people vote but sure if you can skip Thaumcraft it make no sense

**Comment by Prometheus0000** [comment]
I guess you forgot about this @Dream-Master ? The vote was pretty clear
image

**Comment by Dream-Master** [comment]
But i like some things can be obtained in a different way. I dont merge stuff blind even if people 188 vote here. It is a small group compared to the player base we have. The vote ist a test for me to see a result but i dont follow it 100%.

**Comment by Prometheus0000** [comment]
> you need magical ingredients. I will do a vote. Let the community make a decision.

> sure a rework is maybe necessary. Lets see what people vote but sure if you can skip Thaumcraft it make no sense

But now you don't want it to change? Maybe? I can't tell from what you're saying. And you don't care about the results of the vote that you wanted. I don't understand what you _do_ want here then. What does "Let the community make a decision" mean then? Normally, that means leaving the decision up to the community, but apparently you meant something else?

Do you not want to merge the PR? Should I just remove the part that relates to ichorium? Did you want a ticket to discuss the other thaumcraft recipes?

You say you "don't merge stuff blind", but this is from 3 months ago, and you still haven't made any decision, or said what you want.

PS: This repo's comments don't show up in the github channel, so if you could fix it, that would be nice.

**Comment by Dream-Master** [comment]
Let it in there not close it but i thing the last word not spoken about this here. MAybe we need to check more recipes need a change/remove idk since bart left because most of them are made in his bartworks code so far i remeber.

**Comment by Prometheus0000** [comment]
So, you don't want me to do anything? What about the MC recipe though?

**Comment by Dream-Master** [comment]
MC recip ?

**Comment by Prometheus0000** [comment]
@Dream-Master Mysterious Crystal. From #GTNewHorizons/GT-New-Horizons-Modpack#6321.

**Comment by Dream-Master** [comment]
@Prometheus0000 feel free to add those recipe but again why we should remove the ichorium one? You can skip rockets craft the crystal dust why not skip some Thaumcraft stuff as well?

**Comment by Dream-Master** [comment]
ok i merge that and remove the //

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
