### PR TITLE
Magical Nightshade now plantable

### PR DESCRIPTION
**Pull request by Florexiz**
You can use magic essence (obtained from primordial pearl and this crop) to plant previously unobtainable magical nightshade crop

### CODE REVIEW

**Comment by repo-alt** [comment]
How does it work?

**Comment by repo-alt** [comment]
Ok, so it requires block of ichorium below. Does not look very OP, I wonder why bart did not fix it.

**Review by repo-alt — APPROVED** [review]

**Comment by Florexiz** [comment]
image

**Comment by Florexiz** [comment]
Not sure its the way he wanted it to be, but better than nothing I guess

**Pull request merged**
